# Generated by Django 3.2.7 on 2021-10-04 23:41

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('worlds_best_boss_1', models.BooleanField(default=False)),
                ('worlds_best_boss_2', models.BooleanField(default=False)),
                ('worlds_best_boss_3', models.BooleanField(default=False)),
                ('cassanova_1', models.BooleanField(default=False)),
                ('cassanova_2', models.BooleanField(default=False)),
                ('cassanova_3', models.BooleanField(default=False)),
                ('short_and_sweet', models.BooleanField(default=False)),
                ('dickens', models.BooleanField(default=False)),
                ('it_takes_committment_1', models.BooleanField(default=False)),
                ('it_takes_committment_2', models.BooleanField(default=False)),
                ('it_takes_committment_3', models.BooleanField(default=False)),
                ('sleep_mode', models.BooleanField(default=False)),
                ('lunch_break', models.BooleanField(default=False)),
                ('forget_me_not', models.BooleanField(default=False)),
                ('networking_1', models.BooleanField(default=False)),
                ('networking_2', models.BooleanField(default=False)),
                ('networking_3', models.BooleanField(default=False)),
                ('sentimental', models.BooleanField(default=False)),
                ('what_year_is_it', models.BooleanField(default=False)),
                ('nerd', models.BooleanField(default=False)),
                ('old_school', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relationship_type', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('sent_to_email', models.CharField(default='', max_length=100)),
                ('sent_to_phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backend_app.recipient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
