# Generated by Django 3.2.7 on 2021-09-21 00:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_rename_sender_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 21, 0, 6, 37, 289238, tzinfo=utc)),
        ),
    ]
