# Generated by Django 3.2.7 on 2021-09-21 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_message_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
