# Generated by Django 3.2.7 on 2021-09-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_alter_message_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
