# Generated by Django 3.2.7 on 2021-09-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
    ]
